[package]
name = "bubble-rs"
version = "0.1.0"
edition = "2021"
description = "A collection of reusable TUI components for building terminal applications with bubbletea-rs"
license = "MIT"
repository = "https://github.com/your-username/bubble-rs"
keywords = ["tui", "terminal", "bubbletea", "components", "ui"]
categories = ["command-line-utilities", "gui"]
authors = ["Your Name <your.email@example.com>"]

[lib]
name = "bubble_rs"
path = "src/lib.rs"

[dependencies]
crossterm = "0.27"
unicode-width = "0.1"
fuzzy-matcher = "0.3"

[dev-dependencies]
tokio = { version = "1.0", features = ["full"] }

[[example]]
name = "spinner"
path = "examples/spinner.rs"

[[example]]
name = "textinput"
path = "examples/textinput.rs"

[[example]]
name = "list"
path = "examples/list.rs"

[[example]]
name = "progress"
path = "examples/progress.rs"