name: Release

on:
  push:
    tags:
      - 'v*'

env:
  # Ensure release runs without ANSI colors and clipboard dependencies
  NO_COLOR: "1"
  NOCOLOR: "1"
  CARGO_TERM_COLOR: never

jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}

      - name: Run tests (without clipboard)
        run: cargo test --lib --tests --no-default-features

      - name: Run doc tests (without clipboard)
        run: cargo test --doc --no-default-features

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Run clippy (without clipboard)
        run: cargo clippy --lib --tests --no-default-features -- -D warnings

      - name: Publish to crates.io (with default features for users)
        run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}